# -*- coding: utf-8 -*-
"""Midterm_More_Esha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cp8s6Wi28W2KSGXrX5BZ8_C2VNa23ct-
"""

###################################################################
# University of Toronto
# Faculty of Information
# Master of Information Program
# INF 1340H - Programming for Data Science
#
# Student Name: Esha More
# Student Number: 1011832304
# Supervisor: Dr. Maher Elshakankiri
#
#
# Midterm
# Purpose: Conduct descriptive and initial inferential analysis of Coffee Data with user input and output results to a file.
# Date Created: 09-29-2025
# Date Modified: 09-30-2025
###################################################################

# all imports
import pandas as pd # for advanced dataframe functions
import math # for math functions

# checks if file exists, if not then default file is used
def verifyFile(file, file_type):
  if file_type == 'input':
    while file != '':
      try: # if filename exists then do the following
        input_file = pd.read_csv(file+'.csv')
        return input_file
      except: # otherwise ask for another name
        file = input(file+'.csv does not exist. Please try again: ')
    print("No file name entered. Data will be taken from 'synthetic_coffee_health_10000.csv'")
    return pd.read_csv('synthetic_coffee_health_10000.csv')
  elif file_type == 'output':
    if file != '':
      return open(file+'.txt', 'w', newline='')
    else:
      print("No file name provided. Results will be stored at 'midterm-results.txt'")
      return open('midterm-results.txt', 'w', newline='')

# replaces null or empty values with a given input value
# improves readability through the dataset
def dataClean(df, colName):
  for index, row in df.iterrows():
    if row[colName] != None:
      if row[colName] == 0 or row[colName] == 0.0:
        df.at[index, colName] = None
  return df

# get user input on data file and output file
coffee_df = verifyFile(input('Please enter a file name for input: '), 'input')
print()

coffee_df = dataClean(coffee_df, 'Sleep_Hours')

# x = Coffee Intake
# y = Sleep Hours

# finds the max value in a given list
def calcMax(col):
  max = float('-inf')
  for val in col:
    if val != None and val > max:
      max = val
  return max

# finds the min val in a given list
def calcMin(col):
  min = float('inf')
  for val in col:
    if val != None and val < min:
      min = val
  return min

x_max = calcMax(coffee_df['Coffee_Intake'])
x_min = calcMin(coffee_df['Coffee_Intake'])

# calculates the mean from a given list
def calcMean(col):
  return float(col.sum() / len(col))

# calculates the standard deviation from a given list and mean
def calcStdDev(col, mean):
  sum = 0
  for val in col:
    if val != None:
      if type(val) != str:
        sum += (val - mean) ** 2
      else:
        return ('Column must be a numeric type')
  return float(math.sqrt(sum / len(col)))

# calculate the mode of a specified column
def calcMode(col):
  # storing counts of how many times each number appears
  counts = {}
  for val in col:
    if val != None:
      if type(val) != str:
        if val in counts:
          counts[val] += 1
        else:
          counts[val] = 1
      else:
        return ('Column must be a numeric type')

  # calculating the max count
  max = calcMax(counts)
  max_key = ''
  for key, val in counts.items():
    if val != None:
      if val > max:
        max = val
        max_key = key
    else:
      return

  return max_key, max

y_mean = calcMean(coffee_df['Sleep_Hours'])
x_mean = calcMean(coffee_df['Coffee_Intake'])
y_std = calcStdDev(coffee_df['Sleep_Hours'], x_mean)
x_std = calcStdDev(coffee_df['Coffee_Intake'], y_mean)
y_mode, y_count = calcMode(coffee_df['Sleep_Hours'])
x_mode, x_count = calcMode(coffee_df['Coffee_Intake'])

# calculates the covariance between two identified variables
def calcCov(inc_df, var_x, x_mean, var_y, y_mean):
  sum = 0
  for index, row in inc_df.iterrows():
    if row[var_x] != None and row[var_y] != None:
      if type(row[var_x]) != str:
        sum += (row[var_x] - x_mean) * (row[var_y] - y_mean)
      else:
        return ('Column must be a numeric type')
  return sum / (len(inc_df) - 1)

# using covariance to find the correlation between action types and points scored
def calcCorr(cov, x_std, y_std):
  corr = 0
  if x_std > 0 and y_std > 0:
    corr = cov / (x_std * y_std)
  return corr

# identify the strength of the correlation based on ranges
def calcCorrStrength(corr):
  strenght = ''
  if corr > 0.8:
      strength = 'a strong positive'
  elif corr > 0.5 and corr < 0.8:
      strength = 'a positive'
  elif corr < -0.5 and corr > -0.8:
        strength = 'a negative'
  elif corr < -0.8:
      strength = 'a strong negative'
  else:
      strength = 'weak'
  return strength

xy_cov = calcCov(coffee_df, 'Coffee_Intake', x_mean, 'Sleep_Hours', y_mean)
xy_corr = calcCorr(xy_cov, x_std, y_std)
xy_strength = calcCorrStrength(xy_corr)

# linear regression of two variables
def linReg(corr, x_std_dev, y_std_dev, x_mean, y_mean):
  slope = corr * (y_std_dev / x_std_dev)
  y_inter = y_mean - (slope * x_mean)
  return slope, y_inter

# predict the value of y for an x input with the values from linReg function
def predY(slope, y_inter, x):
  return y_inter + (slope * x)

xy_slope, xy_inter = linReg(xy_corr, x_std, y_std, x_mean, y_mean)

# predict how much the user would sleep based on intake of cups of coffee
x_og = float(input('Please enter your cups of coffee intake so we can predict your sleep hours: '))
pred = predY(xy_slope, xy_inter, x_og) # predict y

output = verifyFile(input('Please enter a file name for output: '), 'output')

def cleanOutput(label, val, val_type):
  result = 'The ' + val_type + ' for ' + label + ' is ' + val + '.'
  output.write(result+'\n')
  print(result)

# grouping all outputs together
cleanOutput('Coffee Intake', str(x_max), 'maximum')
cleanOutput('Coffee Intake', str(x_min), 'minimum')

cleanOutput('Sleep Hours', str(round(x_mean, 2)), 'mean')
cleanOutput('Sleep Hours', str(round(x_std, 2)), 'standard deviation')
cleanOutput('Sleep Hours', str(x_mode), 'mode')
cleanOutput('Coffee Intake', str(round(y_mean, 2)), 'mean')
cleanOutput('Coffee Intake', str(round(y_std, 2)), 'standard deviation')
cleanOutput('Coffee Intake', str(y_mode), 'mode')

cleanOutput('Sleep Hours and Coffee Intake', str(round(xy_cov,2)), 'covariance')
cleanOutput('Sleep Hours and Coffee Intake', str(round(xy_corr, 2)), 'correlation coefficient')
cleanOutput('Sleep Hours and Coffee Intake', str(xy_strength), 'correlation strength')

cleanOutput('Sleep Hours and Coffee Intake', str(round(xy_slope, 2)), 'sloppe')
cleanOutput('Sleep Hours and Coffee Intake', str(round(xy_inter, 2)), 'y-intercept')
cleanOutput(str(x_og) + ' cups of Coffee Intake', str(round(pred, 2)), 'sleep hours prediction')
output.close()